### ISSUE TITLE
How to connect graph to project 

### ISSUE THREAD

**Issue by harshvardhanabhinav** [sadityakumar9211/medichain-nextjs#7]
How can i connect graph to project

**Comment by harshvardhanabhinav** [comment]
This .env file edited and deployed but didnt work

**Comment by harshvardhanabhinav** [comment]
Also i want to ask graph is not connected so it is showing this problem or smart contract is not deployed so?

**Comment by harshvardhanabhinav** [comment]
Invalid account: #0 for network: rinkeby - private key too short, expected 32 bytes
  * Invalid account: #1 for network: rinkeby - private key too short, expected 32 bytes
  * Invalid account: #2 for network: rinkeby - private key too short, expected 32 bytes
  * Invalid account: #3 for network: rinkeby - private key too short, expected 32 bytes
  * Invalid account: #0 for network: mainnet - private key too short, expected 32 bytes
  * Invalid account: #1 for network: mainnet - private key too short, expected 32 bytes
  * Invalid account: #2 for network: mainnet - private key too short, expected 32 bytes
  * Invalid account: #3 for network: mainnet - private key too short, expected 32 bytes
  * Invalid account: #0 for network: polygon - private key too short, expected 32 bytes
  * Invalid account: #1 for network: polygon - private key too short, expected 32 bytes
  * Invalid account: #2 for network: polygon - private key too short, expected 32 bytes
  * Invalid account: #3 for network: polygon - private key too short, expected 32 bytes
  *  Please help to solve this error after importing correct private key then also comes

**Comment by harshvardhanabhinav** [comment]
In goerli i have 0.0195 eth before deploying can this be a issue?

**Comment by sadityakumar9211** [comment]
This might be an issue. You'll see `insufficient funds` message in your console when you try to deploy if you have insufficient funds.
